language: python
python:
- '3.8'
- '3.9'
install:
- pip install -r requirements-dev.txt
script:
- pytest --cov=banyan tests/
- flake8 --exit-zero
- python setup.py sdist bdist_wheel
after_success:
- codecov
- if [[ $TRAVIS_TAG ]]; then twine upload dist/*; fi
deploy:
  provider: releases
  api_key:
    secure: X3uP2TLX4qbozBxyQDO257SiaYZGycqAqSIH0QuXYhBzqBke8e1xI25F6aWl/WnP9HFWlQuhx5TKCj+SVoWqmULvcLIRTg37+L7lPmuG6YjXpJ0qfbEE5TTTk+xhulf+BYqJhTnvKqNsPY8YBfdTOy6Es9G/BY2zctjkoOlqN0vQgqq3XCjw1Ej8MsZRCL/+lsRhjVXrKURlxRMLSZAXxoSpwGvXAr+2oZLhPMkcTZuqMAfxp6J6uKAjiylXtpl6uJY2Tdux6YgLlb//chE7XHpZYdyJ0/YibzZ1Psz2rJC+iKiMNoyZVQv1eUv3g/p5VguxbKiHJVML6zLT026jyP9XDWDCDDCTDwFekhXQvKr/JuZdaDxo2Ty8hQ4R1CdTDg64j9rCrU/F2Av0uH7c3PiD/kaa35jiPg29TWdcbhV4uUYBzBebbwkGJo3xfCJFGVSIQ0DJdbNZNPb61BvDnNUY8Jfxgha93j4x1wd1nkytty3639kI3ECu5eZnSOpJ1ufWazYziY3M5Sr7wFtJZ0izKjszcaLxi6MebQhVTvSGu3Elf4CyWVhLNzRkAZt75xDfQwxX5G4q96qr822fpu7hsjfWzXX/Z2voaxReLRGFCWhWlO9qOYiplNYIdlBFPxlNjgrcv9Ly9xMOCgjYVmzuqV1Apd+mupOUKGeDjNQ=
  file_glob: true
  file: dist/*
  on:
    tags: true
  skip_cleanup: true
  draft: true
  overwrite: true
notifications:
  slack:
    rooms:
    - secure: CQKz7HtlrUJVmy062QILGzq2AcuvaQrZ3yUSCzKfPyWf/hXJY7UWCWLutAGDMuH3RD913xxujYN5EmN/ZaxUoYIL72x8nDEE3E7vqt+s01yzgjrVMIpZ0cWwQKaQyomFrqw8gJFxBccdRU5ZtOCDDrDdchiHX4iXYrj84k0K1JvEVXijK8PxCRzNZWbBq6XiNF3cuT8ZNJY8jl0GEkTqSFrXVrP6x9zFQgx597uzEL3xgvvqtbPH8sbmgdb44pZUM535rUXDwecOxOoNKa+YpWWJUDIk5QH9upQGr83aA5q7qxxpIqee5h8epp44tNK9Qio5JPyTLu9AHi4UUK+4X+mO8W04+PUjPZNagYDq/QEkpqH2e5XjAfxO9Z9MlYjGDrvG94VOzBaF7wObYQnEEhccSJLS71D1UmIw+NktZCZU7d5Acopjlnl3aaps23TMan5QEi7oW7PiTtPwSmERBU0ZiSayzpW0jYAxyLBTjmeoHMkjIRJH8mwmjejt9A6RxeDwI0Qh2OZgDB5JZwNcN93ZFAGnxkZgYfGjFMCOExuvsE5StPUgy9/DoxymH93h+17xKYuUOPBtYuCkoGGoQYZdrvDY9WCqS1CZrD70jXl0w0GrV/eCoY8xA9Mgk1POAlWuEuimwLkwcuHC8hgUjTy4pTObpvnF7wnUw0bFBkc=
