# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from openapi_client.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    ENDUSER_FACING = "enduser_facing"
    AUDIT_LOG = "audit_log"
    CUSTOMER_FACING_NAMESPACE = "CUSTOMER_FACING_NAMESPACE"
    DEVICE = "device"
    REGISTERED_SERVICE = "registered_service"
    SECURITY_POLICY = "security_policy"
    SECURITY_ROLE = "security_role"
    ENDUSER = "enduser"
    EVENT = "event"
    NETAGENT = "netagent"
    SECURITY_EVENT = "security_event"
    BUNDLE = "bundle"
    TRUSTSCORE_INTEGRATION = "trustscore_integration"
    SERVICE_BUNDLE = "service_bundle"
    ACCESS_ACTIVITY = "access_activity"
    ACCESS_TIER = "access_tier"
    ACCESS_TIER_TUNNEL = "access_tier_tunnel"
    DEPRECATED = "deprecated"
    API_KEY = "api_key"
    APP_DEPLOYMENT = "app_deployment"
    AUTH_USER_METADATA = "auth_user_metadata"
    BANYANIDP = "banyanidp"
    BASIC_REPORT = "basic_report"
    CERTIFICATE = "certificate"
    CLOUD_RESOURCE = "cloud_resource"
    CLOUD_RESOURCE_SERVICE = "cloud_resource_service"
    COMMAND_CENTER_SETTING = "command_center_setting"
    SUPERADMIN = "superadmin"
    EXTERNALCERT = "externalcert"
    GLOBAL_DOMAIN_DIRECTORY = "global_domain_directory"
    HEALTH = "health"
    INVITE_CODE = "invite_code"
    ORG = "org"
    SAML = "saml"
    PRODUCT_ANALYTICS = "product_analytics"
    REFRESH_TOKEN = "refresh_token"
    REGISTERED_DOMAIN = "registered_domain"
    SERVICE_CONNECTION_TEST = "service_connection_test"
    SAASAPP = "saasapp"
    SATELLITE = "satellite"
    SATELLITE_FACING = "satellite_facing"
    SERVICE_TUNNEL = "service_tunnel"
    SENTINELONE = "sentinelone"
    SERVICE_ACCOUNT = "service_account"
    SERVICE_METADATA = "service_metadata"
    SHIELD = "shield"
    SIGNUP = "signup"
    TRUSTSCORE = "trustscore"
    TRUSTSCORE_EXCLUSION = "trustscore_exclusion"
    TUNNEL_CIDR = "tunnel_cidr"
    TUNNEL_RESOURCE = "tunnel_resource"
    UNREGISTERED_DEVICE = "unregistered_device"
