# coding: utf-8

"""
    Banyan Rest APIs

    This swagger spec contains list of all Banyan APIs.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_api_v1_admin_saml.get import V1ApiV1AdminSamlGet
from openapi_client.paths.v1_api_v1_admin_setup_saml.post import V1ApiV1AdminSetupSamlPost
from openapi_client.paths.v1_saml_metadata.get import V1SamlMetadataGet


class SamlApi(
    V1ApiV1AdminSamlGet,
    V1ApiV1AdminSetupSamlPost,
    V1SamlMetadataGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
