# coding: utf-8

"""
    Banyan Rest APIs

    This swagger spec contains list of all Banyan APIs.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_security_events.get import V1SecurityEventsGet
from openapi_client.paths.v1_security_events_type_count.get import V1SecurityEventsTypeCountGet


class SecurityEventApi(
    V1SecurityEventsGet,
    V1SecurityEventsTypeCountGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
