# coding: utf-8

"""
    Banyan Rest APIs

    This swagger spec contains list of all Banyan APIs.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v2_service_metadata_service_id.get import V2ServiceMetadataServiceIdGet
from openapi_client.paths.v2_service_metadata_services.get import V2ServiceMetadataServicesGet


class ServiceMetadataApi(
    V2ServiceMetadataServiceIdGet,
    V2ServiceMetadataServicesGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
