# coding: utf-8

"""
    Banyan Rest APIs

    This swagger spec contains list of all Banyan APIs.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v2_integration_crowdstrike.post import V2IntegrationCrowdstrikePost
from openapi_client.paths.v2_integration_crowdstrike.put import V2IntegrationCrowdstrikePut
from openapi_client.paths.v2_integration.delete import V2IntegrationDelete
from openapi_client.paths.v2_integration_device_identity_command.delete import V2IntegrationDeviceIdentityCommandDelete
from openapi_client.paths.v2_integration_device_identity_command.get import V2IntegrationDeviceIdentityCommandGet
from openapi_client.paths.v2_integration_device_identity_command.post import V2IntegrationDeviceIdentityCommandPost
from openapi_client.paths.v2_integration_device_identity_command.put import V2IntegrationDeviceIdentityCommandPut
from openapi_client.paths.v2_integration.get import V2IntegrationGet
from openapi_client.paths.v2_integration_partner.get import V2IntegrationPartnerGet
from openapi_client.paths.v2_integration.post import V2IntegrationPost
from openapi_client.paths.v2_integration.put import V2IntegrationPut
from openapi_client.paths.v2_integration_signal.delete import V2IntegrationSignalDelete
from openapi_client.paths.v2_integration_signal.get import V2IntegrationSignalGet
from openapi_client.paths.v2_integration_signal.post import V2IntegrationSignalPost
from openapi_client.paths.v2_integration_signal.put import V2IntegrationSignalPut
from openapi_client.paths.v2_integration_sync_config.get import V2IntegrationSyncConfigGet
from openapi_client.paths.v2_integration_sync_config.post import V2IntegrationSyncConfigPost
from openapi_client.paths.v2_integration_sync_config.put import V2IntegrationSyncConfigPut
from openapi_client.paths.v2_integration_sync_stats_device_csv.get import V2IntegrationSyncStatsDeviceCsvGet
from openapi_client.paths.v2_integration_sync_stats.get import V2IntegrationSyncStatsGet
from openapi_client.paths.v2_integration_test_credentials_crowdstrike.post import V2IntegrationTestCredentialsCrowdstrikePost
from openapi_client.paths.v2_integration_test_credentials.get import V2IntegrationTestCredentialsGet


class TrustscoreIntegrationApi(
    V2IntegrationCrowdstrikePost,
    V2IntegrationCrowdstrikePut,
    V2IntegrationDelete,
    V2IntegrationDeviceIdentityCommandDelete,
    V2IntegrationDeviceIdentityCommandGet,
    V2IntegrationDeviceIdentityCommandPost,
    V2IntegrationDeviceIdentityCommandPut,
    V2IntegrationGet,
    V2IntegrationPartnerGet,
    V2IntegrationPost,
    V2IntegrationPut,
    V2IntegrationSignalDelete,
    V2IntegrationSignalGet,
    V2IntegrationSignalPost,
    V2IntegrationSignalPut,
    V2IntegrationSyncConfigGet,
    V2IntegrationSyncConfigPost,
    V2IntegrationSyncConfigPut,
    V2IntegrationSyncStatsDeviceCsvGet,
    V2IntegrationSyncStatsGet,
    V2IntegrationTestCredentialsCrowdstrikePost,
    V2IntegrationTestCredentialsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
